os: linux
install:
  - sudo apt-get install -y --no-install-recommends lib32stdc++6 libstdc++6 > /dev/null
  - cd ..
  - git clone https://github.com/flutter/flutter.git -b stable
  - export PATH="$PATH":"$HOME/.pub-cache/bin"
  - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
  - cd ConcordiaGO
  - flutter precache
  - flutter doctor -v
after_success:
  - tool/send.sh success $WEBHOOK_URL
after_failure:
  - tool/send.sh failure $WEBHOOK_URL

jobs:
  include:
    - stage: tests
      name: "Static Tests"
      os: linux
      script:
        - flutter analyze

    - stage: tests
      name: "Unit Tests"
      os: linux
      script:
        - pub global activate coverage
        - flutter test --coverage && bash <(curl -s https://codecov.io/bash) -f coverage/lcov.info

stages:
  - tests

# Only building master means that we don't run two builds for each pull request.
branches:
  only:
    - develop
    - master

cache:
  directories:
    - "$HOME/.pub-cache"