language: bash
os: linux
services:
  - docker
install:
  - sudo apt-get install -y --no-install-recommends lib32stdc++6 libstdc++6 > /dev/null
  - cd ..
  - git clone https://github.com/flutter/flutter.git -b stable
  - export PATH="$PATH":"$HOME/.pub-cache/bin"
  - export PATH=`pwd`/flutter/bin:$(pwd)/flutter/bin/cache/dart-sdk/bin:$PATH
  - cd ConcordiaGO
  - flutter precache

jobs:
  include:
    - stage: tests
      name: "Static Tests"
      script:
        - dartfmt . --fix -n --set-exit-if-changed
        - flutter analyze

    - stage: tests
      name: "Unit Tests"
      script:
        - flutter test --machine > tests.output
        - flutter test --coverage
        - docker run -t -u=root -v "$(pwd):/usr/src" -w "/usr/src" clearedkinkajou/concordia-go:latest -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_LOGIN

stages:
  - tests

# Only building master means that we don't run two builds for each pull request.
branches:
  only:
    - develop
    - master

cache:
  directories:
    - "$HOME/.pub-cache"