name: concordia_go
description: A concordia maps application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  google_maps_flutter: ^0.5.21+15
  google_maps_util:
  geolocator: ^5.2.0
  bloc: ^3.0.0
  flutter_bloc: ^3.1.0
  equatable: ^1.0.3
  url_launcher: ^5.4.2
  http : any
  sliding_up_panel: ^1.0.0
  photo_view: ^0.9.2
  flutter_svg: ^0.17.2
  xml: ^3.5.0
  location_permissions: ^2.0.5
  validators: ^2.0.0+1
  device_calendar: ^3.0.0+3
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_name: ^0.0.1
  pedantic: ^1.8.0+1
  bloc_test: any
  mockito: ^4.1.1

flutter_launcher_name:
  name: "Concordia GO"

flutter:
  uses-material-design: true
  assets:
    - assets/headers/ConcordiaGOHeader.png
    - assets/logos/ConcordiaGOLogo.png